### ISSUE TITLE
dimensions

### ISSUE THREAD

**Issue by ay4me** [julian-upc/2015-algorithms#6]
We have in the init-method the code-line self.dim = len(coos[0]).
Does that mean we have to consider that we might get more then 2 dimensions later on?
That would make turning much more difficult.

**Comment by TheUndertalker** [comment]
That would make turning w/o a given turning axis impossible. turn90() should only be called if its a 2D pentomino. I guess you can even give out some error if it isn't.

**Comment by julian-upc** [comment]
While it's correct that ```turn90()``` will only ever be called on a 2d pentomino, there's no reason to restrict everything to this scenario. In fact, later we will want to run dancing links also on 3d pentominos (and other shapes), so what should probably happen is that ```turn90()``` should raise an exception when called with a pentomino of greater dimension.

**Comment by ay4me** [comment]
Couldn't we also add a parameter to the method that defines the axis we turn around, then we can also turn in 3D or more.

**Comment by julian-upc** [comment]
I think that's a good idea in general, and most probably we'll end up doing just that.

However, right now we're not yet at the point where that's important, so coding this now would take away precious time from completing our current goal, which is to get the dancing links algorithm up and running.

I think that in this instance, it's justified to leave the function in less than it's full generality, because it's still entirely adequate for the job at hand. 

But these decisions have to be thought through very carefully. Usually I'm all for coding procedures in a very general way (so that you don't have to generalize it later), but here it seems like too much effort for too little reward. YMMV.
